application: apt-nebula-157221
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /map
  static_files: map.html
  upload: map\.html

libraries:
- name: webapp2
  version: "2.5.2"
